import { Guest } from "@/types";

const baseTime = "2025-12-26T10:00:00.000Z";

export const MOCK_GUESTS: Guest[] = [
    {
        id: "g1",
        name: "김철수",
        organization: "경기도청",
        position: "도지사",
        seatNumber: null,
        status: "arrived",
        type: "vip",
        biography: "제35대 경기도지사, 체육회장 겸임",
        protocolNotes: ["인사말씀", "대표 축사"],
        updatedAt: baseTime,
    },
    {
        id: "g2",
        name: "이영희",
        organization: "대한체육회",
        position: "사무총장",
        seatNumber: null,
        status: "not_arrived",
        type: "vip",
        updatedAt: baseTime,
    },
    {
        id: "g3",
        name: "박광민",
        organization: "경기도체육회",
        position: "과장",
        seatNumber: null,
        status: "arrived",
        type: "staff",
        protocolNotes: ["진행요원"],
        updatedAt: baseTime,
    },
    {
        id: "g4",
        name: "최민수",
        organization: "수원시청",
        position: "시장",
        seatNumber: null,
        status: "cancelled",
        type: "regular",
        updatedAt: baseTime,
    },
    {
        id: "g5",
        name: "홍길동",
        organization: "화성시체육회",
        position: "회장",
        seatNumber: null,
        status: "not_arrived",
        type: "regular",
        biography: "체육 발전 공로자",
        protocolNotes: ["대리수상: 아들 홍길서"],
        updatedAt: baseTime,
    },
    {
        id: "g6",
        name: "강감찬",
        organization: "용인시청",
        position: "부시장",
        seatNumber: null,
        status: "arrived",
        type: "regular",
        updatedAt: baseTime,
    },
    {
        id: "g7",
        name: "신사임당",
        organization: "안산시체육회",
        position: "이사",
        seatNumber: null,
        status: "not_arrived",
        type: "regular",
        updatedAt: baseTime,
    },
    {
        id: "g8",
        name: "이순신",
        organization: "부천시청",
        position: "체육과장",
        seatNumber: null,
        status: "arrived",
        type: "staff",
        updatedAt: baseTime,
    },
];
